### ISSUE TITLE
Please remove this repository

### ISSUE THREAD

**Issue by danielgordon10** [dvlshah/Re3#7]
Hi there,
This is the author of Re3. While I am not forcing you to remove it, it is confusing for people to find it here because they may think it's the original. I have made the code available at https://gitlab.com/danielgordon10/re3-tensorflow and you can fork it on Gitlab just like you can on Github. Either that or I would at least appreciate you updating your Readme to be very clear at the top that this is a clone and not the original, and to point people to the original code.

Thank You,
Daniel

**Comment by dvlshah** [comment]
Sorry for not mentioning the originality of work appropriately. I would immediately change the readme. Also, my intention was to make this important piece of work accessible to others on Github to others and not claiming this work as an original piece of mine in any way.
